name: gocd
home: https://gocd.org/
version: 0.1.0
appVersion: 17.12.0
description: A GoCD Helm chart for Kubernetes. GoCD is an Open source continuous delivery server to model and visualize complex workflows with ease.
icon: https://gocd.github.io/assets/images/go-icon-black-192x192.svg
keywords:
- gocd
- ci
- cd
- ci/cd
- continuous-integration
- continuous-delivery
- continuous-deployment
- continuous-testing
sources:
- https://github.com/gocd/gocd
maintainers:
- name: ThoughtWorks, Inc.
  email: godev+k8s@thoughtworks.com
