{{- if and .Values.server.persistence.enabled (not .Values.server.persistence.godata.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gocd.fullname" . }}-data
  labels:
    app: {{ template "gocd.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    component: server
spec:
  accessModes:
    - {{ .Values.server.persistence.godata.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.godata.size | quote }}
{{- if .Values.server.persistence.godata.storageClass }}
  storageClassName: {{ .Values.server.persistence.godata.storageClass }}
{{- else }}
  storageClassName: ""
{{- end }}
{{- if .Values.server.persistence.godata.pvSelector }}
  selector:
{{ toYaml .Values.server.persistence.godata.pvSelector | indent 4 }}
{{- end }}
{{- end }}
