apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gocd.name" . }}-server-deployment
  labels:
    app: {{ template "gocd.name" . }}-server
    chart: "{{ template "gocd.name" . }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    role: server
spec:
  {{- if le .Values.server.replicaCount 1.0 }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "gocd.name" . }}-server
  template:
    metadata:
      labels:
        app: {{ template "gocd.name" . }}-server
        role: server
    spec:
      {{- if .Values.server.persistence.enabled }}
      volumes:
        - name: godata-vol
          persistentVolumeClaim:
            claimName: {{ .Values.server.persistence.godata.name }}
        - name: homego-vol
          persistentVolumeClaim:
            claimName: {{ .Values.server.persistence.homego.name }}
      {{- end }}
      containers:
        - name: {{ template "gocd.name" . }}-server
          {{- if .Values.server.image.tag }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          {{- else }}
          image: "{{ .Values.server.image.repository }}:v{{ default .Chart.AppVersion .Values.app.version }}"
          {{- end }}
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          env:
            {{- if .Values.server.env.goServerSystemProperties }}
            - name: GO_SERVER_SYSTEM_PROPERTIES
              value: {{ .Values.server.env.goServerSystemProperties }}
            {{- end }}
          ports:
            - containerPort: 8153
            - containerPort: 8154
          livenessProbe:
            httpGet:
              path: /go/api/v1/health
              port: 8153
            initialDelaySeconds: {{ .Values.server.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.healthCheck.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /go/api/v1/health
              port: 8153
            initialDelaySeconds: {{ .Values.server.healthCheck.initialDelaySeconds }}
          {{- if .Values.server.persistence.enabled }}
          volumeMounts:
          - name: godata-vol
            mountPath: /godata
          - name: homego-vol
            mountPath: /home/go
          {{- end }}
          resources:
{{ toYaml .Values.server.resources | indent 12 }}
    {{- if .Values.server.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.server.nodeSelector | indent 8 }}
    {{- end }}
