{{- if .Values.server.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "gocd.name" . }}-server-ingress
  labels:
    app: {{ template "gocd.name" . }}-server
    chart: "{{ template "gocd.name" . }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    role: server
  annotations:
    {{- range $key, $value := .Values.server.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  backend:
    serviceName: {{ template "gocd.name" . }}-server-service
    servicePort: {{ .Values.server.service.httpPort }}
  rules:
    {{- range $host := .Values.server.ingress.hosts }}
    - host: {{ $host }}
  {{- end -}}
{{- end -}}
