apiVersion: v1
kind: Service
metadata:
  name: {{ template "gocd.name" . }}-server-service
  labels:
    app: {{ template "gocd.name" . }}-server
    chart: "{{ template "gocd.name" . }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    role: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.httpPort }}
      targetPort: 8153
      {{- if .Values.server.service.nodeHttpPort }}
      nodePort: {{ .Values.server.service.nodeHttpPort }}
      {{- end}}
      protocol: TCP
      name: http

    - port: {{ .Values.server.service.httpsPort }}
      targetPort: 8154
      {{- if .Values.server.service.nodeHttpsPort }}
      nodePort: {{ .Values.server.service.nodeHttpsPort }}
      {{- end}}
      protocol: TCP
      name: https
  selector:
    app: {{ template "gocd.name" . }}-server
    role: server
